### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by colindaven** [jfarek/xatlas#3]
It would ease installation to have an example of downloading a compatible HTSlib and pointing the configure at it.

I have tried multiple variants of the below and do not know what to expect or where it wants htslib/hts.h to be present. Linking ln -s does not work

cheers

./configure --enable-multithreading --with-htslib-lib=htslib-1.4.1
rcug@hpc03:/mnt/ngsnfs/tools/xatlas$ ./configure --enable-multithreading --with-htslib-lib=htslib-1.4.1
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking htslib/hts.h usability... no
checking htslib/hts.h presence... no
checking for htslib/hts.h... no
configure: error: Failed to find HTSLib headers

**Comment by jfarek** [comment]
Hi,

If the htslib header files subdirectory (``htslib/``) is also located in the same directory ``htslib-1.4.1``, you can run configure as:

``./configure --enable-multithreading --with-htslib=htslib-1.4.1``

If ``htslib/`` is located somewhere else, you can specify its location with the ``--with-htslib-include=`` option:

``./configure --enable-multithreading --with-htslib-lib=htslib-1.4.1 --with-htslib-include=/path/to/htslib_dir``

**Comment by colindaven** [comment]
Repeatedly tried with all sorts of new downloads, various htslib, compiled or non-compiled htslibs, no signs of progress, thanks anyway.

**Comment by loreseeker** [comment]
@colindaven   Hi, I ran into the same issue, but was able to build alignstats-0.7 on a clean ubuntu:16.04 after adding a make install command for htslib-1.9 and to run it after exporting LD_LIBRARY_PATH to include htslib-1.9 directory
