### ISSUE TITLE
Combining per sample vcf files into multisample vcf 

### ISSUE THREAD

**Issue by danangcrysnanto** [jfarek/xatlas#4]
Hi

Thanks for the great tools.
Is there any recommendation (or capability in xatlas) to merge single sample vcf produced by xatlas to the multi sample vcf. 
I have tried several possibility:
* Run the xatlas in `vcf mode` and then combined  using a simple `bcftools merge` . But there is a no way to differentiate between no call `./.` to the homozygous reference `0/0`  and i found that `bcftools` infers all non-variants site to be missing 
* Run the xatlas in `gvcf mode` and then combined using `gvcftools merge_variants`. However, the `gvcftools` does not recommended to do [this](https://sites.google.com/site/gvcftools/home/configuration-and-analysis)
I am usually do  `imputation` after variant calling. Thus the differentiation between non-ref and missing is important. 

Thanks in advance for the help.

**Comment by jfarek** [comment]
Hi,

xAtlas itself performs only single-sample variant calling. For creating multi-sample VCFs and pVCFs, our group has been using a version of [GLNexus](https://github.com/dnanexus-rnd/GLnexus) for the gVCF merging steps. GLNexus is more on the heavy side compared to bcftools and gvcftools, but we have found it a very useful tool for our analyses. We haven't attempted to merge xAtlas VCFs or gVCFs with either bcftools or gvcftools.

**Comment by danangcrysnanto** [comment]
Hi
Appreciate for your feedback. I will try the GLnexus.
