### ISSUE TITLE
Missing shared library?

### ISSUE THREAD

**Issue by slzarate** [jfarek/xatlas#5]
I have the latest version of htslib installed from http://www.htslib.org/download/ (v1.9), but when I try to run xatlas, I get the following error:

`/xatlas: error while loading shared libraries: libhts.so.2: cannot open shared object file: No such file or directory`

Any suggestions?

**Comment by kkapuria3** [comment]
I get the same error. Let me know if you find a way to work around.

**Comment by slzarate** [comment]
Thanks for reminding me about this issue. The problem was that I had compiled the binary in Ubuntu 16.04, but was trying to run it in 14.04.
